drop table BATCH_STEP_EXECUTION_CONTEXT ;
drop table BATCH_STEP_EXECUTION ;
drop table BATCH_JOB_EXECUTION_PARAMS ;
drop table BATCH_JOB_EXECUTION_CONTEXT ;
drop table BATCH_JOB_EXECUTION ;
drop table BATCH_JOB_INSTANCE ;
